services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped
    ports:
      - "5432:5432" # optional: expose locally for DB clients

  web:
    build:
      context: .
      target: dev
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -lc "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db_data:

