# Generated by Django 5.1.12 on 2025-09-16 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_soft_delete_to_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_topics', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True, default='')),
                ('insights', models.JSONField(blank=True, default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='core.document')),
            ],
            options={
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['document', '-analyzed_at'], name='core_docume_documen_7eb4ea_idx')],
            },
        ),
    ]
