# Generated by Django 5.1.12 on 2025-09-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_pdf_url_to_url_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='signer',
            name='sign_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
