# Generated by Django 5.1.12 on 2025-09-17 23:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_sign_url_to_signer'),
    ]

    operations = [
        migrations.AddField(
            model_name='signer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signer',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='last_view_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='times_viewed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
